DELETE http://localhost:8080/events/1/register
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQG1haWwuY29tIiwiZXhwIjoxNzIyMjgyMjk5LCJ1c2VySWQiOjF9.iumlqNN29ipvJBxmKoD5q7ctyRWBu0Nq_7T6kmD_eeE